version: 0.1
loglevel: debug
storage:
  filesystem:
    rootdirectory: /var/lib/registry
  delete:
    enabled: true

http:
  addr: :5000

auth:
  token:
    realm: https://auth.example.tld/auth
    service: "Docker Registry"
    issuer: "ACME Auth Server"
    rootcertbundle: /etc/ssl/auth_server/certificate.crt
