version: "3"

networks:
  registry:
    driver: bridge
services:
  traefik:
    image: traefik:alpine
    container_name: traefik
    hostname: traefik
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /home/ec2-user/docker_distribution/volumes/traefik/traefik.toml:/etc/traefik/traefik.toml
    ports:
      - "80:80"
      - "443:443"
  auth_server:
    build: ./auth_server
    image: "auth_server:20190309"
    container_name: auth_server
    hostname: auth_server
    restart: unless-stopped
    volumes:
      - /home/ec2-user/docker_distribution/volumes/ssl/:/etc/auth_server/ssl
      - /home/ec2-user/docker_distribution/volumes/auth_server/auth.yml:/etc/auth_server/auth.yml
    labels:
      - "traefik.frontend.rule=Host:auth.example.tld"
      - "traefik.port=5001"
      - "traefik.enable=true"
  registry:
    image: registry:2
    container_name: registry
    hostname: registry
    restart: unless-stopped
    volumes:
      - registry:/var/lib/registry
      - /home/ec2-user/docker_distribution/volumes/ssl/:/etc/docker/registry/ssl
      - /home/ec2-user/docker_distribution/volumes/registry/config.yml:/etc/docker/registry/config.yml
    labels:
      - "traefik.frontend.rule=Host:example.tld"
      - "traefik.port=5000"
      - "traefik.enable=true"
    depends_on:
      - auth_server
volumes:
  registry:
