defaultEntryPoints = ["http", "https"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]
  [entryPoints.api]
  address = ":8080"

[api]
entryPoint = "api"

[acme]
email = "email@example.tld"
entryPoint = "https"
storage = "/etc/traefik/acme/acme.json"
onHostRule = true
  [acme.httpChallenge]
  entryPoint = "http"

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "example.tld"
exposedByDefault = false
watch = true

[web]
address = ":8080"
